from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SiteDesignStandard:
    """Non-negotiable design rules for every website generated by the B2B bot."""

    name: str = "Premium AI Studio"
    minimum_quality_score: int = 90

    required_traits: tuple[str, ...] = (
        "cinematic above-the-fold hero with a clear conversion CTA",
        "oversized editorial typography with strong visual hierarchy",
        "generous whitespace and asymmetric modern composition",
        "premium card surfaces with subtle borders, blur, depth, or glass effects",
        "tasteful gradients, ambient lighting, or textured backgrounds",
        "custom iconography and polished service/product presentation",
        "high-quality photography or art direction appropriate to the business",
        "micro-interactions and restrained motion for hover, reveal, and navigation states",
        "responsive layouts that feel intentionally designed on mobile, tablet, and desktop",
        "high-contrast conversion sections with obvious trust signals",
        "modern FAQ, testimonials, case-study, and contact experiences",
        "consistent spacing, radius, shadow, type scale, and component system",
    )

    forbidden_traits: tuple[str, ...] = (
        "generic WordPress or page-builder appearance",
        "dated boxed navigation bars",
        "tiny typography",
        "dense walls of text",
        "stock-template section repetition",
        "cheap gradient buttons",
        "low-resolution or obviously generic imagery",
        "inconsistent icon styles",
        "desktop-first layouts that collapse awkwardly on mobile",
        "visual clutter without hierarchy",
    )

    generator_prompt: str = """
Design and build this website as if it came from a top-tier modern AI product studio.
Do not imitate or copy any specific company's proprietary website. Use an original premium
editorial aesthetic: sophisticated typography, exceptional spacing, cinematic composition,
subtle depth, tasteful motion, polished cards, confident calls to action, and a coherent
design system.

The result must look custom-designed rather than templated. Every section should earn its
place and have a clear conversion purpose. Use responsive art direction, strong accessibility,
fast-loading assets, and refined interaction states. Avoid dated local-business website
patterns, generic WordPress styling, repetitive card grids, and weak stock imagery.

Before output, self-review the site for visual hierarchy, originality, responsiveness,
conversion clarity, typography, spacing consistency, image quality, trust signals, and motion.
If the design would plausibly be described as 'basic', 'dated', or 'template-like', redesign it
before returning the result.
""".strip()


DEFAULT_SITE_DESIGN_STANDARD = SiteDesignStandard()


def build_site_generation_prompt(*, business_name: str, business_type: str, offer: str = "") -> str:
    offer_line = f"\nPrimary offer: {offer}" if offer else ""
    return (
        f"Business: {business_name}\n"
        f"Industry: {business_type}{offer_line}\n\n"
        f"{DEFAULT_SITE_DESIGN_STANDARD.generator_prompt}\n\n"
        "Required visual traits:\n- "
        + "\n- ".join(DEFAULT_SITE_DESIGN_STANDARD.required_traits)
        + "\n\nForbidden traits:\n- "
        + "\n- ".join(DEFAULT_SITE_DESIGN_STANDARD.forbidden_traits)
    )
